# Generated by Django 4.2.6 on 2023-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaster_name", models.CharField(max_length=255)),
                ("plasterweight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("coverage_by_metre", models.FloatField()),
                (
                    "plaster_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="plaster_images/"
                    ),
                ),
            ],
        ),
    ]
