# Generated by Django 4.2.6 on 2023-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0002_plaster_plaster_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaster",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
