# Generated by Django 4.2.6 on 2023-10-12 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0003_plaster_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plaster",
            old_name="coverage_by_metre",
            new_name="coverage_kg_per_mm_per_metre",
        ),
    ]
