# Generated by Django 4.2.6 on 2023-10-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calculator",
            "0004_rename_coverage_by_metre_plaster_coverage_kg_per_mm_per_metre",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plaster",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
