# Generated by Django 4.2.6 on 2023-10-18 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0006_plaster_tds_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaster",
            name="sds_url",
            field=models.URLField(
                default=1, validators=[django.core.validators.URLValidator()]
            ),
            preserve_default=False,
        ),
    ]
